version: '3.6'
services:
  mongodb:
    image: mongo
    container_name: mongo_dev
    restart: always
    ports:
      - '27017:27017'
    networks:
      - dev

  mongo-seed:
    build: ./mongo-seed
    container_name: mongo_seed
    links:
      - mongodb
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - dev

  contact-service:
    image: nute/contact
    ports:
      - '14001:8080'
    links:
      - mongodb
    depends_on:
      - mongodb
      - mongo-seed
    networks:
      - dev

  contact-frontend:
    build:
      context: ./contact-frontend
      dockerfile: Dockerfile.e2e
    container_name: contact-frontend.e2e
    ports:
      - '4222:4200'
    depends_on:
      - contact-service
    networks:
      - dev

networks:
  dev:
    driver: bridge
